### ISSUE TITLE
Name with . causes compilation errors.

### ISSUE THREAD

**Issue by belav** [JetBrains/resharper-rider-plugin#42]
When generating a new solution, if your name has a period there will be a few classes that cannot compile.
```
dotnet new resharper-rider-plugin --name CSharpier.Rider --include-samples
```

**Comment by matkoch** [comment]
If someone knows how to fix this I'm all ears, but otherwise, I don't think it's worth taking time to investigate. Particularly in your case, the `Rider` postfix is unnecessary, because the template already adds that. Moreover, I believe that when generating from the template _without_ samples, there should be no such issue.

**Comment by belav** [comment]
Yeah I realized after generating it that the `.Rider` was unnecessary, and I also just noticed that there is a note that does say the name should be letters only.
I believe it would be possible to get the name working with a . based on this page - https://github.com/dotnet/templating/wiki/Naming-and-default-value-forms
Which I think would require changing the name everywhere in the repo.... which is probably not worth the effort.
