### ISSUE TITLE
EAP branch

### ISSUE THREAD

**Issue by nojaf** [JetBrains/resharper-rider-plugin#56]
Hello,

I tend to revisit this repository when there is a new Rider version out.
To see how I can update my own plugin.
Would it be possible to also have an eap branch that updates the template to support the latest EAP version?
I understand if this might be too much hassle to maintain.
Let me know what you think.

**Comment by ForNeVeR** [comment]
You see, this repository isn't meant for bleeding-edge plugin development purposes. Mostly, it's for people who like to rely on stable versions of Rider. We can try updating it from time to time, but since we don't use teh template ourselves (because most of the plugins in development are already created and thus require no template), there's no guarantee it will always work.

For directions on updating to the latest versions of Rider, feel free to watch our official plugins (which **always** publish together with the EAP, and so there **is** a guarantee they will work and build against it):
- [resharper-fsharp](https://github.com/JetBrains/resharper-fsharp)
- [resharper-unity](https://github.com/JetBrains/resharper-unity)

As a smaller example, I can recommend my [AvaloniaRider](https://github.com/ForNeVeR/AvaloniaRider) plugin: it updates to EAP builds, too, with some lag.

And if you have any questions on updating your plugin, feel free to direct them into our private plugin writers Slack channel.

**Comment by nojaf** [comment]
Hello, your Avalonia example is what I'm after.
That would work for me.
Thanks
