### ISSUE TITLE
Template does not include the actual plugin project in the solution it creates

### ISSUE THREAD

**Issue by bradykelly** [JetBrains/resharper-rider-plugin#71]
I have just tried this template for the first time, and was quite confused for some minutes because almost nothing was included in the solution.  Then I find that the code I'm looking for in another solution in the same folder as the solution the template created. This is not at all a tidy way to structure solutions. Now I have to choose between the solution I created and the generated solution, and even if I try the generated solution, it doesn't include any easily identified place to add my own code. The two README files I can find only include links to images and zero text. 

I know this isn't a paid-for product that I can expect more from, and that some effort is required on my part to set things up, but I really think this could be done in a better, simple, more component oriented and configurable way. Expect quite a few PRs from me in this regard.

**Comment by matkoch** [comment]
I don't think what you're talking about is really actionable. If you follow the README – using .NET CLI directly – the generated content _does_ include a solution file that references all necessary projects. This is the solution file you want. How did you generate from the template?

What exactly should the generated README contain? The images/links you're talking about are for you to add the plugin ids to get a badge, once they're uploaded. You can also clear the content if you want.

Your code is added to one of the two non-test projects. The other non-test project will automatically include the file, since the two project files are located in the same folder.
